"""add_indices_for_sync_optimization

Revision ID: b36aa411c248
Revises: b2c3d4e5f6a7
Create Date: 2026-05-19 17:58:07.722515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36aa411c248'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_external_mappings_external_id', ['external_id'], unique=False)
        batch_op.create_index('idx_external_mappings_external_id_platform', ['external_id', 'platform'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_projects_slug'), ['slug'])

    with op.batch_alter_table('task_delegations', schema=None) as batch_op:
        batch_op.create_index('idx_delegations_target_status', ['target_instance_id', 'status'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_deleted', ['deleted'], unique=False)
        batch_op.create_index('idx_tasks_external', ['external_id', 'external_platform'], unique=False)
        batch_op.create_index('idx_tasks_instance_id', ['instance_id'], unique=False)
        batch_op.create_index('idx_tasks_owner', ['owner'], unique=False)
        batch_op.create_index('idx_tasks_requester', ['requester'], unique=False)
        batch_op.create_index('idx_tasks_updated_at', ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_updated_at')
        batch_op.drop_index('idx_tasks_requester')
        batch_op.drop_index('idx_tasks_owner')
        batch_op.drop_index('idx_tasks_instance_id')
        batch_op.drop_index('idx_tasks_external')
        batch_op.drop_index('idx_tasks_deleted')

    with op.batch_alter_table('task_delegations', schema=None) as batch_op:
        batch_op.drop_index('idx_delegations_target_status')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_projects_slug'), type_='unique')

    with op.batch_alter_table('external_mappings', schema=None) as batch_op:
        batch_op.drop_index('idx_external_mappings_external_id_platform')
        batch_op.drop_index('idx_external_mappings_external_id')

    # ### end Alembic commands ###
